### ISSUE TITLE
默认不带type嘛 图标开头的

### ISSUE THREAD

**Issue by ghost** [tw93/cz-emoji-chinese#2]
能不能增加个配置 能添加type

**Comment by tw93** [comment]
可以的 明天我加

**Comment by tw93** [comment]
{
  "config": {
    "cz-emoji-chinese": {
      "types": [
        {
          "emoji": "🌟",
          "code": ":star2:",
          "description": "A new feature",
          "name": "feature"
        }
      ]
    }
  }
}
