### ISSUE TITLE
当我单独配置了cz-emoji-chinese，出现了奇怪的问题

### ISSUE THREAD

**Issue by cwandev** [tw93/cz-emoji-chinese#3]
这是我的package.json 

```
"config": {
    "commitizen": {
      "path": "./node_modules/cz-emoji-chinese"
    },
    "cz-emoji-chinese": {
      "types": [
        {
          "emoji": "🌟",
          "code": "🌟",
          "description": "A new feature",
          "name": "feat"
        }
      ]
    }
  }
```

步骤 ——》 git cz \ 设置更改类型 | 指定范围 \ 简短的描述 

到这一步，无论如何也输入不了任何内容

**Comment by tw93** [comment]
辛苦参考这个即可 https://github.com/tw93/cz-emoji-chinese/blob/master/lib/types.json

<img width="421" alt="image" src="https://user-images.githubusercontent.com/8736212/194743786-20cc5c46-58f7-4f28-b8d4-92195a80519d.png">
这个是不是就是你需要的这个，基本不需要配置

**Comment by cwandev** [comment]
是的，新问题得到了解决，不过我希望在emoji前面，增加一个type，用来说明提交的类型。我不确定 #2 是不是也是同一个述求。

我希望是这样：

feat: :sparkles: message .

**Comment by tw93** [comment]
@CharleeWa 抱歉，你说的这个诉求，没有听太懂
> 希望在emoji前面，增加一个type
你可以试试在我的代码里面改，然后ok了，直接提pr即可

**Comment by cwandev** [comment]
@tw93 嗯嗯
